name: Integration Tests
on:
  pull_request:
    branches:
      - 'crdb'
  push:
    branches:
      - 'crdb'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Disable Swap
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
      - uses: actions/checkout@v2
        with:
          path: kuby-core/
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Bundler
        run: gem install bundler
      - name: Install Kind
        run: kuby-core/scripts/install-kind.sh
      - name: Run Tests
        run: kuby-core/scripts/integration.sh
        env:
          PREBUNDLER_ACCESS_KEY_ID: "${{ secrets.PREBUNDLER_ACCESS_KEY_ID }}"
          PREBUNDLER_SECRET_ACCESS_KEY: "${{ secrets.PREBUNDLER_SECRET_ACCESS_KEY }}"
          RAILS_MASTER_KEY: "${{ secrets.RAILS_MASTER_KEY }}"
